name: wakareeru_app
description: "Flutter client for Wakareeru inference."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  adaptive_platform_ui:
    path: /Users/sakiko/Desktop/NipaPlay-Reload/packages/adaptive_platform_ui
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
